package com.company.oop.taskmanagementsytemgroup11.commands.enums;

public enum CommandType {
    CREATEMEMBER,
    SHOWALLPEOPLE,
    CREATETEAM,
    SHOWALLTEAMS,
    SHOWMEMBERACTIVITY,
    SOHWTEAMACTIVITY,
    ADDMEMBER,
    SHOWTEAMEMBERS,
    CREATEBOARD,
    SHOWALLTEAMSBOARDS,
    SHOWBOARDSACTIVITY,
    ASSIGNTASK,
    UNASSIGNTASK,
    ADDCOMMENT,
    CHANGEPRIORITY,
    CHANGESEVERITY,
    CHANGESIZE,
    CHANGERATING,
    CREATE,
    CHANGESTATUS
}
