package com.company.oop.taskmanagementsytemgroup11.commands.enums;

public enum CommandType {
    CREATEMEMBER,
    SHOWALLPEOPLE,
    CREATETEAM,
    SHOWALLTEAMS,
    SHOWMEMBERACTIVITY,
    SHOWTEAMACTIVITY,
    ADDMEMBER,
    SHOWTEAMMEMBERS,
    CREATEBOARD,
    SHOWALLTEAMSBOARDS,
    SHOWBOARDACTIVITY,
    ASSIGNTASK,
    UNASSIGNTASK,
    ADDCOMMENT,
    CHANGEPRIORITY,
    CHANGESEVERITY,
    CHANGESIZE,
    CHANGERATING,
    CREATE,
    CHANGESTATUS,
    SHOWTASKACTIVITY;
}
