package com.company.oop.taskmanagementsytemgroup11.commands.enums;

import com.company.oop.taskmanagementsytemgroup11.commands.BaseCommand;

public enum CommandType {
    CREATEMEMBER,
    SHOWALLPEOPLE,
    CREATETEAM,
    SHOWALLTEAMS,
    SHOWMEMBERACTIVITY,
    SHOWTEAMACTIVITY,
    ADDMEMBER,
    SHOWTEAMMEMBERS,
    CREATEBOARD,
    SHOWALLTEAMBOARDS,
    SHOWBOARDACTIVITY,
    ASSIGNTASK,
    UNASSIGNTASK,
    ADDCOMMENT,
    CHANGEPRIORITY,
    CHANGESEVERITY,
    CHANGESIZE,
    CHANGERATING,
    CREATEBUG,
    CREATESTORY,
    CHANGESTATUS,
    SHOWTASKACTIVITY,
    CREATEFEEDBACK,
    LISTTASKS,
    LISTSTORIES,
    LISTBUGS,
    LISTTASKWITHASSIGNEE,

    LISTFEEDBAKS;

}
